services:
  next:
    build: 
      context: packages/swim
      args:
        BASE_PATH: http://localhost:3000
        MONGO_USERNAME: root
        MONGO_PASSWORD: example
        MONGO_CONNECTION: mongodb://mongo:27017
    restart: always
    environment:
      BASE_PATH: http://localhost:3000
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_CONNECTION: mongodb://mongo:27017
    depends_on:
      - mongo
  proxy:
    build: 
      context: packages/proxy
    restart: always
    ports: 
      - 80:80
      - 443:443
    environment:
      PROXY_TARGET: http://next:3000
      PRIVATE_KEY_PATH: /
      CERTIFICATE_PATH: /
    depends_on:
      - next
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false