services:
#  proxy:
#    build: 
#      context: packages/proxy
#    restart: always
#    ports: 
#      - 80:80
#      - 443:443
#    volumes:
#      - /etc/aaa/:/data/cert
#    environment:
#      PROXY_TARGET: http://next:3000
#      PRIVATE_KEY_PATH: /data/cert/privkey1.pem
#      CERTIFICATE_PATH: /data/cert/cert1.pem
#      HTTP_REDIRECT_LOCATION: http://www.google.com
#    depends_on:
#      - next
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /data/dlrg-swim/mongo:/data/db
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017
      ME_CONFIG_BASICAUTH: false